### ISSUE TITLE
What is chunked?

### ISSUE THREAD

**Issue by poespas** [BernardJeremy/node-twitch-link#3]
Hi there,

What's the difference between a chunked m3u8 playlist and the others? There doesn't seem much difference, also I've noticed that chunked sometimes entails 1080p, and not listed seperated.

Thanks,
Poespas

**Comment by BernardJeremy** [comment]
Hi Poespas,

Sorry for the delay : "chunked" content seems to be the "source" quality stream, without any compression or reduced resolution.
